### ISSUE TITLE
Some images "pushed down" 50% in IE

### ISSUE THREAD

**Issue by HBOlsen** [constancecchen/object-fit-polyfill#11]
Hi,

I'm having an issue where the first image in a Bootstrap caraousel renders correct but any images after the initial one is "pushed down" 50% of the carousel high. This only happens in IE and Edge, Chrome shows all images as expected using normal CSS...

The first image:
![correct_render](https://cloud.githubusercontent.com/assets/22715517/21849528/82fec010-d806-11e6-8b72-e05a0efa4e62.PNG)

Incorrect rendering:
![incorrect_render](https://cloud.githubusercontent.com/assets/22715517/21849526/82fe3a82-d806-11e6-9e4f-4c90178b5ea1.PNG)

If I disable this CSS property in Edge, it shows all images correctly
![css_property](https://cloud.githubusercontent.com/assets/22715517/21849527/82fe3eec-d806-11e6-928d-606055499c7d.PNG)

Is this a bug or am I doing something wrong? My implementation of the "inner carousel" is as follows:

```
<div class="carousel-inner" role="listbox">
    <div class="item active">
        <img data-object-fit src="images/carousel/MyImage1.jpg" alt="Image">
    </div>
    <div class="item">
        <img data-object-fit src="images/carousel/MyImage2.jpg" alt="Image">
     </div>
     <div class="item">
         <img data-object-fit src="images/carousel/MyImage3.jpg" alt="Image">
     </div>
     <div class="item">
         <img data-object-fit src="images/carousel/MyImage4.jpg" alt="Image">
     </div>
</div>
```

**Comment by cee-chen** [comment]
Hm, we might be in for a world of hurt here - depending on which carousel lib you're using, Bootstrap might be settings its own inline styles and overriding the polyfill. Hopefully not, though! :)

If it's not JS interference, my best guess based on the inspector screenshot is that the polyfill is having difficulty accurately getting the height of the `.item` wrapper (hence why the negative `margin-top` is missing). If you could shoot me a link to the page, I can inspect and let you know for sure :)

**Comment by HBOlsen** [comment]
Hi Constance and thanks for the quick reply :)

I'm using the carousel shipped with Bootstrap v3.3.1 or 3.3.7 if I remember correctly. The site is still in development and thus it's not live yet. However, I have copied parts of the source and all relevant CSS into a [CodePen](http://codepen.io/anon/pen/PWNKYb?editors=1100) for you. As far as I can test with IE and Edge from here, the issue shows up as described in my post above.

I've linked the Pen directly to your "dist/objectFitPolyfill.min.js"-file, so changes done to that file should be reflected within a few minutes.

**Comment by cee-chen** [comment]
Thanks very much for the link! I've figured out the issue - Bootstrap's CSS/carousel animation relies on this:

```
.carousel-inner>.item {
    display: none;
}
```

And unfortunately `display: none` zeroes out an element's height, which explains why the polyfill is incorrectly calculating the height of `.item`.

Two solutions I can suggest:

1) Try another carousel lib that doesn't rely on display: none - I personally use [Slick](https://kenwheeler.github.io/slick/) slider :)

2) Intercept Bootstrap's JS and call `objectFitPolyfill();` every time their sliding action occurs. Looks like they have an [event](https://getbootstrap.com/javascript/#carousel-events) we can hook onto:

```
$('#newsCarousel').on('slide.bs.carousel', function () {
  objectFitPolyfill();
})
```

It's not super performant since it's re-checking the entire page for object-fit images every time the carousel slides, but it solves the problem I suppose :) You can check out [this Codepen fork](https://codepen.io/constancechen/pen/KaMerP) to confirm that it works in IE!

**Comment by HBOlsen** [comment]
Sorry for the late reply, I've been working on a few other projects lately 😄 

I've attempted to change to the Slick slider but unfortunately the entire slider disappears when I add the data-object-fit="cover" attribute. If I disable "autoplay" it will show the first image(at whatever resolution the image has), but once you navigate to the next image they will all disappear(including the first one).

The div "slick-track" gets loads of "object-fit-polyfill" classes, so something is definitely wrong...

Have you got any sample code where you've used Slick slider with object fit?

**Comment by cee-chen** [comment]
Hey hey!

No problem at all, here's an example CodePen with Slick and the polyfill:

https://codepen.io/constancechen/pen/zNaJYv

I tested on IE Edge and it looks to be working. Let me know if you have questions at all :)

**Comment by HBOlsen** [comment]
This worked like a dream, thank you very much!
