### ISSUE TITLE
TypeError: objectFitPolyfill is not a function

### ISSUE THREAD

**Issue by nextgenthemes** [constancecchen/object-fit-polyfill#12]
`TypeError: objectFitPolyfill is not a function`

I get this error in Firefox/Chromuim with version 2.0

It points to the lines at the bottom if the files where this functions is called. (I tested this locally with the uncompressed files)

Live example: https://www.asoundeffect.com/oscar-nominated-sound-arrival-deepwater-horizon-lala-land-hacksaw-ridge/

**Comment by cee-chen** [comment]
Gah, sorry about that - completely my bad! I was testing in IE (which returns a usable function) and forgot to check in Chrome and Firefox, which returns early, resulting in undefined errors. This should be fixed now in the latest commit - let me know if it's working for you!

**Comment by nextgenthemes** [comment]
Yes works, thanks.
