### ISSUE TITLE
Please correct bower file reference

### ISSUE THREAD

**Issue by jagdishmastek** [constancecchen/object-fit-polyfill#15]
Please correct the file name in bower.json file 

"main": "dist/objectFitPolyfill.js", it should be "main": "dist/objectFitPolyfill.min.js",

Jagdish

**Comment by cee-chen** [comment]
Oops, terribly sorry about that careless mistake! Fixed in https://github.com/constancecchen/object-fit-polyfill/commit/266c3831f518ee283bc04e36fa2a18aa7be56b4c :)
