### ISSUE TITLE
Error in script

### ISSUE THREAD

**Issue by jagdishmastek** [constancecchen/object-fit-polyfill#16]
Hi,

I got following error in script.

Uncaught ReferenceError: objectFitPolyfill is not defined error in objectFitPolyfill.min.js:1  in google chrome & mozilla firefox browsers.

**Comment by cee-chen** [comment]
1. What browser are you in?
2. Are you using the latest version of objectFitPolyfill (2.0.2, updated 4 days ago)?

**Comment by jagdishmastek** [comment]
Yes, I am using latest version & not working below browsers.
1) Google Chrome (Version 56.0.2924.87)
2) Mozilla Firefox (Version 51.0.1)

Please refer attached screenshot
![error](https://cloud.githubusercontent.com/assets/14260428/23350810/2bd5e726-fce3-11e6-83d8-7b96d2b979c2.png)

**Comment by hyshka** [comment]
I get the same error using webpack to build the un-minified version.

v2.0.1 works, v2.0.2 throws the error. I am assuming it's related to commit: constancecchen/object-fit-polyfill@6bbe79b84093e0e89ade18009c51686c8c5e1852

**Comment by cee-chen** [comment]
Hey all, so sorry for the delay in response! Can you let me know if the latest dist files work for you? I tested with webpack and was able to get it working, but haven't tested with other bundlers yet. If you let me know what module loader you're using (Require, etc.) I can try setting those up and debugging as well.

**Comment by jagdishmastek** [comment]
I am using bower package manager & require.js for module loader.

**Comment by hyshka** [comment]
The latest src+dist code you have in master works for me @constancecchen! Thanks.

**Comment by cedeber** [comment]
Hi. The 2.0.2 is definitely broken. Doesn't work with babelify either. Everything works again with current github data.

**Comment by cee-chen** [comment]
Ah, sorry for the delay - since current master seems to be working for people, I'll bump up to the package versions to 2.0.3 to prevent further confusion :) Please feel free to re-open the issue if you run into more problems!

**Comment by delikeyki95** [comment]
In my case, I get a "not define" error in IE9. Do I checked in the IE11 Developer Tools? 
Does IE9 actually work with out error message?

**Comment by cee-chen** [comment]
@delikeyki95 Apologies, I just tested on IE9 and while I'm not getting a define error, I am getting an error because I changed a line to use `classList.add()`, which IE9 doesn't support. Sorry for the oversight - I've tested on IE9, 11, Edge, Android 4.1, and iOS 6, and it should be working now. Let me know if the latest master fixes the issue for you.

If it's still not working - please open a new issue specifically for IE9! Thanks!

**Comment by delikeyki95** [comment]
@constancecchen  Thank you very much!!  It is working.  :)
