### ISSUE TITLE
How to npm install/import the basic version

### ISSUE THREAD

**Issue by jelmerdemaat** [constancecchen/object-fit-polyfill#17]
Hi! Great plugin, using it all the time. 👍 

I was wondering in what way I can import the basic version from npm in my JavaScript. Right now I have done:

```sh
npm install --save objectFitPolyfill
```

And in my JS:

```js
import 'objectFitPolyfill';
```

Compiled via Babel. That works. But I want the basic version. How do I include that? I would like to do something like:

```js
import 'objectFitPolyfill/basic';
// or
import basic from 'objectFitPolyfill';
// or
import { basic } from 'objectFitPolyfill';
```

Which doesn't seem to work. Any advice on this?

**Comment by cee-chen** [comment]
It's not super pretty, but you can do this:

```js
require('objectFitPolyfill/dist/objectFitPolyfill.basic.min');
```

or in ES6:

```js
import 'objectFitPolyfill/dist/objectFitPolyfill.basic.min';
```

Does that help at all? I so, I can add that to the README :) I know the verbose file name is kind of an eyesore here, apologies for that! If you handle your own concatenation + uglifying in your pipeline, you could save yourself 4 characters (haha!) and do this:

```js
import 'objectFitPolyfill/src/objectFitPolyfill.basic';
```

**Comment by jelmerdemaat** [comment]
That does work, thanks!
