### ISSUE TITLE
Image only loads after window is resize once in Edge 13/14

### ISSUE THREAD

**Issue by bdbch** [constancecchen/object-fit-polyfill#2]

**Comment by bdbch** [comment]
Browser: IE10, IE11, Edge 13, Edge 14
Using Picture-Element

Image is only visible after the window is resized once.

**Comment by bdbch** [comment]
This is caused because I used the picture as an absolute element, the script changes the picture element to relative

**Comment by hendrikeng** [comment]
I am having the same issue even with relative elements ...how did u solve the issue ?

**Comment by bdbch** [comment]
I think I just wrapped the image-wrapper with another absolute element so the inner element doesn't  care if it's relative.
