### ISSUE TITLE
Undo feature

### ISSUE THREAD

**Issue by vendelin8** [constancecchen/object-fit-polyfill#20]
Hi,

It would be nice to have a possibility to undo the object-fit property. Let's say I wan't to remove object-fit from my page dynamically. Maybe through a data property of the dom node, eg. data-object-fit-undoable. And so if it's set, then saving all the changed styles to some variable, and when I change the style back, I could call it by some function undoObjectFit($media). Or if it's better, undo everything with one call, but the first one would be enough for me.

**Comment by cee-chen** [comment]
This is probably not within the scope of this polyfill, sorry. 😞  Feel free to fork/clone the repo and add that feature for your personal use!
