### ISSUE TITLE
Edge17 still has only has partial support

### ISSUE THREAD

**Issue by sebbdk** [constancecchen/object-fit-polyfill#35]
In edge 17 object-fit is not applied on <video>.

Edge 17 only has partial support for object-fit, see https://caniuse.com/#feat=object-fit.
The fix for edge 16 does not apply it self for Edge 17, since this poly-fill only looks for "Edge/16.".

I suggest just adding a regex until it has been confirmed fixed proper like:
`var isEdge16 = window.navigator.userAgent.match(/Edge\/\d\d./) !== null`

**Comment by cee-chen** [comment]
Really appreciate you opening this issue and PR - thanks! Also, praying for the day where this is finally fixed on Edge :)
