### ISSUE TITLE
TypeError: objectFitPolyfill is not a function

### ISSUE THREAD

**Issue by EnriqueDev** [constancecchen/object-fit-polyfill#39]
I know this issue was opened already but I am experimenting the same errors, is there a workaround for this?

**Comment by cee-chen** [comment]
That's strange. What browser are you using, and are you seeing the same error on the [demo page](https://constancechen.me/object-fit-polyfill/)?

If the answer to the above is no, you might be using an outdated version of objectFitPolyfill.

**Comment by EnriqueDev** [comment]
No, the problem was I am using react and SSR. To use it properly you need to use require() or it wont be added to the webpack bundle. Maybe it is worth to put it on the docs so that people won't open issues like this in the future.

Either way, I cant really get your polyfill working on IE / Edge even following the guides. The video gets centered and occupies the full width of the viewport but as I diminish the window length the height wont occupy the full viewport. Should I attach a listener and call it so that the video gets resized?

Thank you very much for your time.

**Comment by cee-chen** [comment]
Really sorry for the delayed response on this. I'd consider virtual DOM frameworks / SSR support to likely be out of scope for this polyfill. Developers using React, Angular, Vue, etc. essentially need to be familiar enough with the framework and their use case to know what lifecycle hooks to use and when.

It sounds like what's likely happening is that the polyfill is being initialized before anything is actually rendered. You'll need to call `objectFitPolyfill()` manually after your video and its container DOM is rendered. Hope that makes sense!
