### ISSUE TITLE
Please add package.json for npm install.

### ISSUE THREAD

**Issue by nextgenthemes** [constancecchen/object-fit-polyfill#4]
I have heard a lot of critique of bower and a lot of people seem to prefer npm so I opted for that. But npm does not support installing form github repos if they do not have a package.json

**Comment by cee-chen** [comment]
Sorry for not seeing this earlier! This should be done now (also took advantage of this to actually add a gitignore file and Gulp for optional lazy minified file generation). Thanks for the great idea and the prod, and let me know if you run into any issues with the new package.json file!

**Comment by nextgenthemes** [comment]
@constancecchen Thanks, works fine.

**Comment by nextgenthemes** [comment]
But you have to define a repo because there is another project registered with npm that with the same name "object-fit-polyfill" that installs with just `npm install object-fit-polyfill`

**Comment by cee-chen** [comment]
@nextgenthemes It should be defined here: https://github.com/constancecchen/object-fit-polyfill/blob/master/package.json#L13

Is it still not working even with that line? I can rename the project if needed :)

**Comment by nextgenthemes** [comment]
It was and is working, just wanted to point out https://www.npmjs.com/package/object-fit-polyfill is registered to https://github.com/tonipinel/object-fit-polyfill

**Comment by nextgenthemes** [comment]
``` json
  "dependencies": {
    "object-fit-polyfill": "latest"
  },
```

will get tonis package

``` json
  "dependencies": {
    "object-fit-polyfill": "git+https://github.com/constancecchen/object-fit-polyfill"
  },
```

will get yours
