### ISSUE TITLE
Support for canvas elements

### ISSUE THREAD

**Issue by fthues** [constancecchen/object-fit-polyfill#43]
Thanks, great polyfill! Would it be possible to add support for polyfilling `object-fit` on the`canvas` element as well?

**Comment by johndgiese** [comment]
We would also be interested in a work around for the `canvas` element.

**Comment by cee-chen** [comment]
Hey, so sorry it took me so long to get to this (no good excuse, I just needed a kick in the butt)! `<canvas>` should now be supported in the latest 2.2.0 version. I've thrown up an example of it here:

http://constancecchen.github.io/object-fit-polyfill/demo/

Let me know if it works for you! :)

**Comment by fthues** [comment]
Awesome, thanks!
