### ISSUE TITLE
Edge 18

### ISSUE THREAD

**Issue by ghost** [constancecchen/object-fit-polyfill#50]
Dear Constance,
I'm using the basic version with Edge 18 which has support for object-fit and partial support. Still polyfill is being applied. Hope you can help.
Best,
Bilal

**Comment by cee-chen** [comment]
Hey so sorry about this! This should be fixed as of [2.2.1](https://github.com/constancecchen/object-fit-polyfill/releases/tag/2.2.1). Feel free to reopen if you still have issues.
