### ISSUE TITLE
2.3.0 version not visible at asset-packagist.org

### ISSUE THREAD

**Issue by sasanikolic90** [constancecchen/object-fit-polyfill#55]
The latest version is not available with bower: https://asset-packagist.org/package/bower-asset/objectFitPolyfill

Also getting this while installing with composer:
```
  Problem 1
    - The requested package bower-asset/objectfitpolyfill 2.3 exists as bower-asset/objectfitpolyfill[v2.2.0, v2.1.1, v2.1.0, v2.0.5, v2.0.4, v2.0.3, v2.0.2, v2.0.1, v2.0, dev-master] but these are rejected by your constraint.
  Problem 2
    - The requested package bower-asset/objectfitpolyfill (locked at v2.2.0, required as 2.3) is satisfiable by bower-asset/objectfitpolyfill[v2.2.0] but these conflict with your requirements or minimum-stability.
```

**Comment by cee-chen** [comment]
Super sorry, I'm not familiar with bower, but I think it's because I tagged that release `2.3.0` instead of `v2.3.0`. I should have just pushed the latest version with `v2.3.2`. Feel free to re-open or open a new issue if you're still having problems with this!
