### ISSUE TITLE
NPM - is not a function

### ISSUE THREAD

**Issue by TomS-** [constancecchen/object-fit-polyfill#56]
Installing via NPM is causing not a function error when using `objectFitPolyfill();`

```
// JS
import objectFitPolyfill from 'objectFitPolyfill'

// Object Fit Polyfill
objectFitPolyfill();
```
Removing objectFitPolyfill(); stops the error. My webpack config is as follows:
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    entry: path.resolve(__dirname, 'assets', 'main.js'),
    output: {
        path: path.resolve(__dirname, 'assets', 'dist')
    },
    module: {
      rules: [
        {
            test: /\.css$/,
            use: [
                MiniCssExtractPlugin.loader,
                'css-loader',
                'postcss-loader'
            ]
        },
        {
            test: /\.js$/,
            exclude: /node_modules/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['@babel/preset-env']
                }
            }
        }
      ]
    },
    plugins: [
        new MiniCssExtractPlugin()
    ],
    watch: true
}
```

EDIT: 
It's worth knowing the script works using the data attribute. It's just the function that doesn't work.

**Comment by joseph-parsley** [comment]
It seems like this is expecting to use `require`, not imported and then used that way. I had the same issue, but changing the import statement to be `require('objectFitPolyfill');` got rid of the error.

**Comment by cee-chen** [comment]
Apologies for the horrifically late response to this, but I've updated the README with example non-breaking usage for calling objectFitPolyfill in a modern webpack project:

```js
import 'objectFitPolyfill';
// Or:
require('objectFitPolyfill');

// Usage
window.objectFitPolyfill();
```

Hope that helps!
