### ISSUE TITLE
Doesn't work on IE 11 with <figure>

### ISSUE THREAD

**Issue by dianastanciu** [constancecchen/object-fit-polyfill#57]
Hi, thank you for this polyfill. It would be great if this issue could be solved someday.

objectFitPolyfill version:
```
/*----------------------------------------
 * objectFitPolyfill 2.3.0
 *
 * Basic, no-frills version -
 * Defaults to object-fit: cover and object-position: 50% 50%
 *
 * Made by Constance Chen
 * Released under the MIT license
 *
 * https://github.com/constancecchen/object-fit-polyfill
 *--------------------------------------*/

```

HTML
```
<figure>
    <img
           src="Images/img/figure.png"
           alt="Fullwidth Image"
           data-object-fit="cover"
           data-object-position="bottom"
     >
      <figcaption>This is an image caption</figcaption>
</figure>
```

CSS
```
figure {
    img {
      width: 100%;
      max-height: 600px;
      object-fit: cover;
      object-position: bottom;
    }
  }
```

Result in IE11: 
https://prnt.sc/u1gme4

Looks like the `<figure>` tag needs a specific height. 

If I remove this from the `<img>` tag:
```
  data-object-fit="cover"
  data-object-position="bottom"
```
It looks fine, except for the object-fit, as expected. See here: https://prnt.sc/u1glvz

If I add a specific height to the `<figure>` tag, like this:
```
figure {
    min-height: 700px; //here

    img {
      width: 100%;
      max-height: 600px;
      object-fit: cover;
      object-position: bottom;
    }
  }
```

The result is still not the one desired, as the image takes up the entire space and the caption is hidden. See here: https://prnt.sc/u1goax

**Comment by cee-chen** [comment]
Hey Diana, sorry for the very late response on this. 

> Looks like the `<figure>` tag needs a specific height.

Yep, this is noted in the README:

> Please note: This plugin makes the assumption that the parent container is acting as a picture frame, and already has a height & width set.

In this case the `figure` element is the parent container / frame and needs to have a height/width set (see the [example CSS in the README](https://github.com/constancecchen/object-fit-polyfill#usage)). The polyfill is not 100% a 'just drop in a single file and go without any configuration' polyfill from that sense, I apologize for the confusion.

If you're just using this plugin for images and don't want the extra requirements that this polyfill entails, I'd suggest checking out https://github.com/fregante/object-fit-images - a super excellent alternative that has less setup!

Closing this issue as this is working as specified, but feel free to ask more q's if you have them!
