### ISSUE TITLE
JSHint: Don't make functions within a loop.

### ISSUE THREAD

**Issue by nextgenthemes** [constancecchen/object-fit-polyfill#6]
I have Atom setup with JSHint and the rules they use for the Twitter Bootstrap Project.

Its says: for lines [229](https://github.com/constancecchen/object-fit-polyfill/blob/master/src/objectFitPolyfill.js#L229)+239: Don't make functions within a loop.

Not that into JavaScript but it probably would make sense to [move this callback outside of the loop.](https://stackoverflow.com/questions/13082302/js-hint-dont-make-functions-within-a-loop)

Also in the basic file of course.

**Comment by constancecchen** [comment]
JSHint is complaining about the anonymous function, which is fair. I'mt not sure how I feel about declaring a function that gets used twice that's all of one line (really just needing to pass `this` into `objectFit()`. That feels a little bit like an over/micro-optimization to me.

Looking at the code (although it's been a while), I think I _might_ be able to condense it down to `media[i].addEventListener("load", objectFit);`, although I'm not entirely sure if `this` will be correctly passed to `objectFit()` in that case. Reading up [here](https://stackoverflow.com/questions/256754/how-to-pass-arguments-to-addeventlistener-listener-function) and [here](https://toddmotto.com/avoiding-anonymous-javascript-functions/), it appears that it will. I'll test this out here shortly!

**Comment by cee-chen** [comment]
JSHint is complaining about the anonymous function. While normally I do try to avoid those, in this case it's a side effect of addEventListener not allowing params to be passed into its functions. If we try to do `addEventListener("load", objectFit(this))`, it will instead immediately invoke `objectFit()` which is not what we want. See:

https://toddmotto.com/avoiding-anonymous-javascript-functions/#passing-parameters

While I could use `.bind()`, this polyfill does support IE as far back as 9, and it would be a little silly to include a polyfill within a polyfill. Thus, this workaround (which the article greenlights in the very last paragraph).

In this particular case, I think declaring/mapping a new function for this scenario which gets used just twice and would contain 1 line is a bit of an over-optimization. I would just configure JSHint to ignore this personally :)

**Comment by nextgenthemes** [comment]
OK makes sense, just wanted to let you know.
